# Generated by Django 4.2.11 on 2025-10-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('task_type', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_column', models.CharField(max_length=255)),
                ('task', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=32)),
                ('estimator', models.CharField(choices=[('logreg', 'Logistic Regression / Linear Regression'), ('svm', 'SVM (Linear/LinearSVR)'), ('rf', 'Random Forest (Cls/Reg)')], default='logreg', max_length=32)),
                ('cv_folds', models.PositiveIntegerField(default=5)),
                ('ga_params', models.JSONField(blank=True, default=dict)),
                ('best_score', models.FloatField(default=0.0)),
                ('selected_features', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('baselines', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='fs.dataset')),
            ],
        ),
    ]
